
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("805x572")
window.configure(bg = "#FFF2F2")

def page2():
    canvas.destroy()
    
    # image_image_2.destroy()
    # image_2.destory()
    # button_image_1.destroy()
    # button_1.destroy()
    canvas1 = Canvas(
    window,
    bg = "#FFF2F2",
    height = 572,
    width = 804,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
    canvas1.place(x = 0, y = 0)
    canvas1.create_rectangle(
        0.0,
        0.0,
        804.375,
        73.734375,
        fill="#F47C7C",
        outline="")
    
    canvas1.create_text(
        0.0,
        0.0,
        anchor="nw",
        text="BCI System",
        fill="#FFFFFF",
        font=("NotoNastaliqUrdu Bold", 13 * -1)
    )
    
    image_image_3 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_3 = canvas1.create_image(
        134.01555633544922,
        39.703125,
        image=image_image_1
    )
    
    canvas1.create_text(
        212.265625,
        112.27734375,
        anchor="nw",
        text="Configuration Steps",
        fill="#000000",
        font=("NotoMusic Regular", 17 * -1)
    )
    
    canvas1.create_rectangle(
        30.72265625,
        194.94921875,
        706.62109375,
        435.14453125,
        fill="#000000",
        outline="")
    
    image_image_4 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_4 = canvas1.create_image(
        551.9140625,
        246.94921875,
        image=image_image_4
    )
    
    canvas1.create_rectangle(
        609.42578125,
        246.8984375,
        667.51953125,
        247.45703125,
        fill="#000000",
        outline="")
    
    image_image_5 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_5 = canvas1.create_image(
        731.0234375,
        462.70703125,
        image=image_image_5
    )
    
    button_image_6 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_2 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_2.place(
        x=301.640625,
        y=435.14453125,
        width=175.3984375,
        height=66.47265625
    )
    
    canvas1.create_text(
        803.2578125,
        120.65625,
        anchor="nw",
        text="Port Number: ",
        fill="#000000",
        font=("NotoMusic Regular", 17 * -1)
    )
    
    canvas1.create_text(
        1085.90625,
        213.3828125,
        anchor="nw",
        text="Choose Your Controller ",
        fill="#000000",
        font=("NotoMusic Regular", 20 * -1)
    )
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
canvas = Canvas(
    window,
    bg = "#FFF2F2",
    height = 572,
    width = 805,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    140.31597900390625,
    107.33332824707031,
    anchor="nw",
    text="Welcome To BCI  System For \nControlling Mouse & Keyboard",
    fill="#000000",
    font=("NotoMusic Regular", 26 * -1)
)

canvas.create_text(
    6.708343505859375,
    292.9305419921875,
    anchor="nw",
    text="The application works with NeuroSky Mindwave Headset",
    fill="#000000",
    font=("NotoMusic Regular", 17 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    805.0,
    73.79165649414062,
    fill="#F47C7C",
    outline="")

canvas.create_text(
    0.0,
    0.0,
    anchor="nw",
    text="BCI System",
    fill="#FFFFFF",
    font=("NotoNastaliqUrdu Bold", 13 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    134.09713745117188,
    39.708343505859375,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    629.9965209960938,
    364.9236145019531,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=page2,
    relief="flat"
)
button_1.place(
    x=342.125,
    y=443.8680419921875,
    width=175.53472900390625,
    height=66.52430725097656
)


window.resizable(False, False)
window.mainloop()
